### PR TITLE
Update image used by k8s-tools

### PR DESCRIPTION
**Pull request by m00g3n**
**Description**

Update image used by `k8s-tools` to use SHA256 instead tags.

Changes proposed in this pull request:

- update alpine image

**Related issue(s)**

### CODE REVIEW

**Comment by Halamix2** [comment]
This would disable dependabot autobumps

**Comment by dekiel** [comment]
@m00g3n why we need this change?

**Comment by m00g3n** [comment]
@dekiel we wanted to make sure we will not get accidental changes which may happen in case we use tags (like [here](https://github.com/kyma-project/kyma/pull/14951))

**Comment by dekiel** [comment]
@m00g3n If you don't want to have automated updates can you stick to the image SHA in files where you use k8s-tools image?

**Comment by Halamix2** [comment]
We won't implement SHA in the `FROM` field, as this would break Dependabot.
The `k8s-tools` image can still be used and referenced by SHA

**Pull request closed without merging**
